import { Fragment, useEffect, useRef, useState } from 'react';
import { approvePriceBatch, createPriceBatch, deletePricePreset, exportPricing, fetchPriceBatches, fetchPriceHistory, fetchPricePresets, fetchPricing, savePricePreset, type PriceBatch, type PriceChange, type PricePoint, type PricePreset, type PriceType, type PricingFilters, type PricingRow, type PricingTable } from '../api/procurementPricing';
import { procurementErrorText } from '../utils/procurementErrorMessages';
import '../procurementPricing.css';

const label = {bronze:'Бронза',platinum:'Платина'};
const batchLabel: Record<string,string> = {draft:'Черновик',approved:'Утверждён, ожидает передачи',transmitting:'Передаётся — ожидаем ответ 1С',applied:'Применён в 1С',conflict:'Конфликт',error:'Ошибка'};
function localDate(d: Date) {return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function initialFilters(): PricingFilters {const d=new Date();return {start:localDate(new Date(d.getFullYear(),d.getMonth(),1)),end:localDate(new Date(d.getFullYear(),d.getMonth()+1,0)),search:'',subject:'',brand:'',quality:'',trend:'all',sort:'name',descending:false,offset:0,limit:50};}
function number(value: string | number | null | undefined) {return value == null ? 'нет данных' : Number(value).toLocaleString('ru-RU',{maximumFractionDigits:2});}
function safeUrl(value: string | null) {try {const u=new URL(value || '');return ['http:','https:'].includes(u.protocol) ? u.href : undefined;} catch {return undefined;}}

function History({row,start,end}: {row: PricingRow;start:string;end:string}) {
  const [points,setPoints]=useState<PricePoint[] | null>(null);const [error,setError]=useState('');
  useEffect(()=>{let active=true;setPoints(null);setError('');fetchPriceHistory(row.code,start,end).then(p=>{if(active)setPoints(p);}).catch(e=>{if(active)setError(procurementErrorText(e));});return ()=>{active=false;};},[row.code,start,end]);
  if(error)return <p role="alert">{error}</p>;
  if(!points)return <p role="status">Загрузка истории цен…</p>;
  return <div className="pricing-history"><h3>История цен: {row.name}</h3>{(['bronze','platinum'] as PriceType[]).map(kind=>{
    const series=points.filter(p=>p.price_type===kind && p.currency==='RUB');const values=series.map(p=>Number(p.price));
    const max=Math.max(...values,1),min=Math.min(...values,0),range=max-min || 1;
    const from=new Date(start).getTime(),to=new Date(`${end}T23:59:59`).getTime();
    const coords=series.map(p=>`${10+(new Date(p.date).getTime()-from)/Math.max(to-from,1)*580},${110-(Number(p.price)-min)/range*100}`).join(' ');
    const first=values[0],last=values[values.length-1],delta=last-first;
    return <section key={kind}><h4>{label[kind]}</h4>{series.length ? <><svg viewBox="0 0 600 125" role="img" aria-label={`График ${label[kind]} с ${start} по ${end}`}><polyline points={coords} fill="none" stroke={kind==='bronze'?'#996820':'#446d8e'} strokeWidth="2" />{series.map((p,i)=><circle key={`${p.date}-${i}`} cx={10+(new Date(p.date).getTime()-from)/Math.max(to-from,1)*580} cy={110-(Number(p.price)-min)/range*100} r="3"><title>{p.date}: {p.price} ₽</title></circle>)}</svg><p>{number(first)} → {number(last)} ₽ · изменение {number(delta)} ₽ ({first>0?number(delta/first*100):'нет базы'}%)</p><details><summary>Значения графика</summary>{series.map((p,i)=><div key={`${p.date}-${i}`}>{new Date(p.date).toLocaleString('ru-RU')} — {number(p.price)} ₽</div>)}</details></>:<p>Истории за период нет</p>}</section>;
  })}</div>;
}

export function ProcurementPricing() {
  const [filters,setFilters]=useState<PricingFilters>(initialFilters);const [active,setActive]=useState(filters);
  const [data,setData]=useState<PricingTable | null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const [drafts,setDrafts]=useState<Record<string,{row:PricingRow;bronze:string;platinum:string;selected:boolean}>>({});
  const [expanded,setExpanded]=useState<string | null>(null);const [presets,setPresets]=useState<PricePreset[]>([]);const [presetName,setPresetName]=useState('');
  const [batches,setBatches]=useState<PriceBatch[]>([]);const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
  const request=useRef<{key:string;body:string} | null>(null);
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetchPricing(active,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(procurementErrorText(e));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return ()=>controller.abort();},[active,revision]);
  useEffect(()=>{let alive=true;Promise.all([fetchPricePresets(),fetchPriceBatches()]).then(([p,b])=>{if(alive){setPresets(p);setBatches(b);}}).catch(e=>{if(alive)setError(procurementErrorText(e));});return ()=>{alive=false;};},[revision]);
  const setFilter=(key:string,value:string | boolean)=>setFilters(f=>({...f,[key]:value,offset:0}));
  const edit=(row:PricingRow,kind:PriceType,value:string)=>setDrafts(d=>({...d,[row.code]:{...(d[row.code] || {row,bronze:'',platinum:'',selected:true}),[kind]:value}}));
  const changes: PriceChange[]=Object.values(drafts).filter(d=>d.selected).flatMap(d=>(['bronze','platinum'] as PriceType[]).filter(kind=>d[kind].trim()!=='' && Number(d[kind])!==Number(d.row[kind])).map(kind=>({code:d.row.code,price_type:kind,old_price:d.row[kind],new_price:d[kind],currency:'RUB'})));
  const invalid=changes.some(c=>!Number.isFinite(Number(c.new_price)) || Number(c.new_price)<=0);
  async function act(action:()=>Promise<unknown>) {setBusy(true);setError('');try {await action();}catch(e){setError(procurementErrorText(e));}finally{setBusy(false);}}
  function period(months:number) {const d=new Date(),month=months===12?0:Math.floor(d.getMonth()/months)*months;setFilters(f=>({...f,start:localDate(new Date(d.getFullYear(),month,1)),end:localDate(new Date(d.getFullYear(),month+months,0)),offset:0}));}
  async function approve() {const body=JSON.stringify(changes);if(request.current?.body!==body)request.current={key:crypto.randomUUID(),body};const batch=await createPriceBatch(request.current.key,changes);await approvePriceBatch(batch.id,batch.version);setDrafts({});request.current=null;setRevision(r=>r+1);}
  return <main className="order-workspace__content pricing-workspace">
    <header><h1>Ценообразование</h1><p>Бронза и платина по каждому товару. Остальные цены рассчитывает 1С.</p></header>
    <form className="pricing-filters" onSubmit={e=>{e.preventDefault();setActive({...filters,offset:0});}}>
      <div className="pricing-period">{[[1,'Месяц'],[3,'Квартал'],[6,'Полугодие'],[12,'Год']].map(([n,name])=><button type="button" key={n} onClick={()=>period(Number(n))}>{name}</button>)}</div>
      <label>С даты<input type="date" required value={filters.start} onChange={e=>setFilter('start',e.target.value)} /></label><label>По дату<input type="date" required min={filters.start} value={filters.end} onChange={e=>setFilter('end',e.target.value)} /></label>
      <label>Товар или код<input value={filters.search} onChange={e=>setFilter('search',e.target.value)} /></label>
      {(['subject','brand','quality'] as const).map((field,i)=><label key={field}>{['Предмет','Бренд','Качество'][i]}<select value={filters[field]} onChange={e=>setFilter(field,e.target.value)}><option value="">Все</option>{(data?.[(['subjects','brands','qualities'] as const)[i]] || []).map(x=><option key={x}>{x}</option>)}</select></label>)}
      {(['profitability_min','profitability_max','defect_min','defect_max'] as const).map((key,i)=><label key={key}>{['Рентабельность от, %','Рентабельность до, %','Брак от, %','Брак до, %'][i]}<input type="number" step="any" value={filters[key] || ''} onChange={e=>setFilter(key,e.target.value)} /></label>)}
      <label>Динамика<select value={filters.trend} onChange={e=>setFilter('trend',e.target.value)}><option value="all">Любая</option><option value="up">Рост продаж</option><option value="down">Спад продаж</option></select></label>
      <label>Сортировка<select value={filters.sort} onChange={e=>setFilter('sort',e.target.value)}>{Object.entries({name:'Наименование',bronze:'Бронза',platinum:'Платина',sales_qty:'Продажи, шт.',sales_amount:'Выручка',profitability:'Рентабельность',defect_pct:'Брак',dynamics_pct:'Динамика'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
      <label><input type="checkbox" checked={filters.descending} onChange={e=>setFilter('descending',e.target.checked)} />По убыванию</label><button type="submit" disabled={loading}>Применить фильтры</button>
    </form>
    <div className="pricing-actions"><label>Сохранённый фильтр<select defaultValue="" onChange={e=>{const p=presets.find(x=>x.id===Number(e.target.value));if(p){setFilters(p.filters);setActive(p.filters);}}}><option value="">Выбрать…</option>{presets.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Название набора<input value={presetName} onChange={e=>setPresetName(e.target.value)} maxLength={100} /></label><button disabled={busy || !presetName.trim()} onClick={()=>void act(async()=>{await savePricePreset(presetName,filters);setPresets(await fetchPricePresets());})}>Сохранить фильтр</button>{presets.map(p=><button key={p.id} aria-label={`Удалить фильтр ${p.name}`} onClick={()=>void act(async()=>{await deletePricePreset(p.id);setPresets(await fetchPricePresets());})}>× {p.name}</button>)}{(['xlsx','csv'] as const).map(format=><button key={format} disabled={busy || loading || !data} onClick={()=>void act(()=>exportPricing(active,format))}>{format.toUpperCase()}</button>)}</div>
    {error && <p role="alert" className="pricing-error">{error}</p>}{loading && <p role="status">Загрузка данных 1С…</p>}
    {data && <><p>Найдено: {data.total} · данные прочитаны {new Date(data.observed_at).toLocaleString('ru-RU')} · период {data.start} — {data.end}</p>{data.warnings.map(x=><p key={x} role="status">{x}</p>)}<div className="order-workspace__table-wrap"><table className="order-workspace__table"><thead><tr><th>Выбор</th><th>Товар</th><th>Бронза, ₽</th><th>Платина, ₽</th><th>Продажи / выручка</th><th>Динамика</th><th>Рентабельность</th><th>Брак</th><th>Прогноз</th><th>Прошлый год</th><th>Конкуренты</th></tr></thead><tbody>{data.items.map(row=><Fragment key={row.code}><tr><td><input type="checkbox" aria-label={`Выбрать ${row.code}`} checked={drafts[row.code]?.selected || false} onChange={e=>setDrafts(d=>({...d,[row.code]:{...(d[row.code] || {row,bronze:'',platinum:''}),selected:e.target.checked}}))} /></td><td><button onClick={()=>setExpanded(expanded===row.code?null:row.code)}>{row.name}</button><small>{row.code} · {row.quality}</small></td>{(['bronze','platinum'] as PriceType[]).map(kind=><td key={kind}><span>{number(row[kind])}</span><input type="number" min="0.01" step="0.01" aria-label={`Новая ${label[kind]} ${row.code}`} placeholder="Новая цена" value={drafts[row.code]?.[kind] || ''} onChange={e=>edit(row,kind,e.target.value)} disabled={busy} /></td>)}<td>{number(row.sales_qty)} шт.<small>{number(row.sales_amount)} ₽</small></td><td>{number(row.dynamics_pct)}%</td><td>{number(row.profitability)}%</td><td>{number(row.defect_pct)}%<small>{number(row.defect_qty)} / {number(row.sales_qty)} шт.</small></td><td>{number(row.forecast_qty)} шт.<small>{number(row.forecast_amount)} ₽</small>{row.forecast_status!=='ready' && <small>{row.forecast_status==='completed'?'Период завершён':'Недостаточно истории'}</small>}</td><td>{number(row.previous_year_qty)} шт.<small>{number(row.previous_year_amount)} ₽</small></td><td>{row.competitors.length?row.competitors.map((offer,i)=><div key={`${offer.name}-${i}`}><a href={safeUrl(offer.url)} target="_blank" rel="noreferrer">{offer.name}</a>: {number(offer.price)} {offer.currency || '(валюта не указана)'}<small>{offer.collected_at?new Date(offer.collected_at).toLocaleDateString('ru-RU'):'Дата не указана'}</small></div>):'Нет сопоставлений'}</td></tr>{expanded===row.code && <tr><td colSpan={11}><History row={row} start={active.start} end={active.end} /></td></tr>}</Fragment>)}</tbody></table></div>{data.items.length===0 && <p>Нет товаров по выбранным условиям</p>}<div className="pricing-actions"><button disabled={loading || active.offset===0} onClick={()=>setActive(f=>({...f,offset:Math.max(0,f.offset-f.limit)}))}>Назад</button><span>{active.offset+1}–{Math.min(active.offset+active.limit,data.total)} из {data.total}</span><button disabled={loading || active.offset+active.limit>=data.total} onClick={()=>setActive(f=>({...f,offset:f.offset+f.limit}))}>Далее</button></div></>}
    <section className="pricing-review"><h2>Изменения к утверждению</h2>{changes.length ? <><ul>{changes.map(c=><li key={`${c.code}-${c.price_type}`}>{c.code} · {label[c.price_type]}: {number(c.old_price)} → {c.new_price} ₽</li>)}</ul><button disabled={busy || invalid} onClick={()=>void act(approve)}>Утвердить {changes.length} изменений</button><button disabled={busy} onClick={()=>setDrafts({})}>Очистить изменения</button></>:<p>Введите новые цены в таблице и выберите товары.</p>}</section>
    <section><h2>Мои пакеты цен</h2><button disabled={busy} onClick={()=>void act(async()=>setBatches(await fetchPriceBatches()))}>Обновить статусы</button>{batches.map(b=><article key={b.id}><strong>№{b.id} — {batchLabel[b.status] || b.status}</strong>{b.document_number && <span> · Документ 1С {b.document_number}</span>}{b.error && <p role="alert">{b.error}</p>}{b.status==='draft' && <button disabled={busy} onClick={()=>void act(async()=>{await approvePriceBatch(b.id,b.version);setBatches(await fetchPriceBatches());})}>Утвердить пакет №{b.id}</button>}</article>)}</section>
  </main>;
}
